version: 2.1
jobs:
  build:
    machine: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:b6:57:e7:40:4c:8e:78:22:ee:99:de:9f:d1:a2:3b"
      - checkout

      - run:
          name: environment
          command: echo 'export PATH=${HOME}/.cargo/bin:${PATH}' >> $BASH_ENV

      - run:
          name: dependencies
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            rustup target add x86_64-unknown-linux-musl
            sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig # https://github.com/rust-lang/cargo/issues/3900

      - run:
          name: test
          command: cargo test --target=x86_64-unknown-linux-musl

      - run:
          name: compile
          command: cargo build --target=x86_64-unknown-linux-musl --release

      - run:
          name: post
          command: |
            mkdir -p $CIRCLE_ARTIFACTS/bin
            mv target/x86_64-unknown-linux-musl/release/http-log-to-statsd $CIRCLE_ARTIFACTS/bin
